# Backpropagation for single neuron

In [8]:
import numpy as np
weights = np.array([-3.0, -1.0, 2.0])
bias = 1.0
inputs = np.array([1.0, -2.0, 3.0])
target=0
control=0.001
def relu(inp):
    return np.maximum(inp,0)
def relu_diff(inp):
    return np.where(inp>0,1,0)
for i in range(200):
    sample=np.dot(weights,inputs)+bias
    relu_=relu(sample)
    loss=(target-relu_)**2

    dloss=2*relu_
    drelu=relu_diff(sample)
    dsum=1
    dbias=1
    dlin=inputs

    dfinal_loss=dloss*drelu*dsum*dlin
    dfinal_bias=dloss*drelu*dsum*dbias

    bias-=control*dfinal_bias
    weights-=control*dfinal_loss

    print(f"iteration - {i+1}, loss:{loss}")

print(f"final biases - {bias}")
print(f"final weights - {weights}")
    

iteration - 1, loss:36.0
iteration - 2, loss:33.872399999999985
iteration - 3, loss:31.870541159999995
iteration - 4, loss:29.98699217744401
iteration - 5, loss:28.21476093975706
iteration - 6, loss:26.54726856821742
iteration - 7, loss:24.978324995835766
iteration - 8, loss:23.502105988581878
iteration - 9, loss:22.113131524656684
iteration - 10, loss:20.80624545154949
iteration - 11, loss:19.576596345362915
iteration - 12, loss:18.419619501351963
iteration - 13, loss:17.331019988822064
iteration - 14, loss:16.306756707482677
iteration - 15, loss:15.343027386070442
iteration - 16, loss:14.43625446755368
iteration - 17, loss:13.583071828521266
iteration - 18, loss:12.780312283455652
iteration - 19, loss:12.024995827503426
iteration - 20, loss:11.314318574097976
iteration - 21, loss:10.645642346368787
iteration - 22, loss:10.016484883698395
iteration - 23, loss:9.424510627071816
iteration - 24, loss:8.867522049011871
iteration - 25, loss:8.34345149591527
iteration - 26, loss:7.850353512

THUS WE HAVE MINIMIZED THE LOSS WITH EVERY ITEREATION AND HAVE REACHED NEAR TO THE TARGET VALUE

# BACKPROPAGATION FOR A LAYER OF NEURONS
-> Initial approach was to write each and every derivative for each neuron in the for loop and get result as stated earlier

-> New approach we use matrices to handle multiple neurons without coding for every single neuron's weights and baises

# _GRADIENTS OF THE LOSS WITH RESPECT TO WEIGHTS,INPUTS AND BIASES_

In [1]:
import numpy as np
# Passed-in gradient from the next layer
# for the purpose of this example we're going to use
# an array of an incremental gradient values
dvalues = np.array([[1., 1., 1.],
 [2., 2., 2.],
 [3., 3., 3.]])
# We have 3 sets of inputs - samples
inputs = np.array([[1, 2, 3, 2.5],
 [2., 5., -1., 2],
 [-1.5, 2.7, 3.3, -0.8]])
# sum weights of given input
# and multiply by the passed-in gradient for this neuron
dweights = np.dot(inputs.T, dvalues)
print(dweights)

[[ 0.5  0.5  0.5]
 [20.1 20.1 20.1]
 [10.9 10.9 10.9]
 [ 4.1  4.1  4.1]]


In [2]:
import numpy as np
# Passed-in gradient from the next layer
# for the purpose of this example we're going to use
# an array of an incremental gradient values
dvalues = np.array([[1., 1., 1.],
 [2., 2., 2.],
 [3., 3., 3.]])
# One bias for each neuron
# biases are the row vector with a shape (1, neurons)
biases = np.array([[2, 3, 0.5]])
# dbiases - sum values, do this over samples (first axis), keepdims
# since this by default will produce a plain list -
dbiases = np.sum(dvalues, axis=0, keepdims=True)
print(dbiases)

[[6. 6. 6.]]


In [3]:
import numpy as np
# Passed-in gradient from the next layer
# for the purpose of this example we're going to use
# an array of an incremental gradient values
dvalues = np.array([[1., 1., 1.],
 [2., 2., 2.],
 [3., 3., 3.]])
# We have 3 sets of weights - one set for each neuron
# we have 4 inputs, thus 4 weights
# recall that we keep weights transposed
weights = np.array([[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]).T
# sum weights of given input
# and multiply by the passed-in gradient for this neuron
dinputs = np.dot(dvalues, weights.T)
print(dinputs)

[[ 0.44 -0.38 -0.07  1.37]
 [ 0.88 -0.76 -0.14  2.74]
 [ 1.32 -1.14 -0.21  4.11]]
